version: "3.7"
services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - nginx

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    environment:
      - APP_SRV_NAME=localhost
      - APP_SERVICE=app
      - APP_PORT=9000
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
